mysql:
  image: mysql:latest
  ports:
  - "3306:3306"
  environment:
  - MYSQL_ROOT_PASSWORD=p4SSW0rd
  - MYSQL_DATABASE=demo
  - MYSQL_USER=dbuser
  - MYSQL_PASSWORD=dbp4ss
hystrix:
  image: kbastani/hystrix-dashboard
  ports:
   - "7979:7979"
  links:
   - gateway
   - discovery
discovery:
  image: kbastani/discovery-microservice
  ports:
   - "8761:8761"
configserver:
  image: kbastani/config-microservice
  ports:
   - "8888:8888"
  links:
   - discovery
gateway:
  image: kbastani/api-gateway-microservice
  ports:
   - "10000:10000"
  links:
   - discovery
   - configserver
   - user
   - movie
   - recommendation
user:
  image: kbastani/users-microservice
  depends_on:
    - mysql
  environment:
    - DATABASE_HOST=demo-mysql
    - DATABASE_USER=dbuser
    - DATABASE_PASSWORD=dbp4ss
    - DATABASE_NAME=demo
    - DATABASE_PORT=3306
  links:
    - discovery
    - configserver
    - mysql
movie:
  image: kbastani/movie-microservice
  depends_on:
    - mysql
  environment:
    - DATABASE_HOST=demo-mysql
    - DATABASE_USER=dbuser
    - DATABASE_PASSWORD=dbp4ss
    - DATABASE_NAME=demo
    - DATABASE_PORT=3306
  links:
    - discovery
    - configserver
    - mysql
recommendation:
  image: kbastani/recommendation-microservice
  depends_on:
    - mysql
  environment:
    - DATABASE_HOST=demo-mysql
    - DATABASE_USER=dbuser
    - DATABASE_PASSWORD=dbp4ss
    - DATABASE_NAME=demo
    - DATABASE_PORT=3306
  links:
   - discovery
   - configserver
moviesui:
  image: kbastani/movies-ui
  environment:
    - DATABASE_HOST=demo-mysql
    - DATABASE_USER=dbuser
    - DATABASE_PASSWORD=dbp4ss
    - DATABASE_NAME=demo
    - DATABASE_PORT=3306
  depends_on:
    - mysql
  ports:
    - "9006:9006"
  links:
    - discovery
    - configserver
    - mysql