version: '3.3'
services:
  mysql:
    image: mysql:latest
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 100M
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=p4SSW0rd
    - MYSQL_DATABASE=demo
    - MYSQL_USER=dbuser
    - MYSQL_PASSWORD=dbp4ss
  hystrix:
    image: kbastani/hystrix-dashboard
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    ports:
     - "7979:7979"
    links:
     - gateway
     - discovery
  discovery:
    image: kbastani/discovery-microservice
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    ports:
     - "8761:8761"
  configserver:
    image: kbastani/config-microservice
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    ports:
     - "8888:8888"
    links:
     - discovery
  gateway:
    image: kbastani/api-gateway-microservice
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    ports:
     - "10000:10000"
    links:
     - discovery
     - configserver
     - user
     - movie
     - recommendation
  user:
    image: kbastani/users-microservice
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    depends_on:
      - mysql
    environment:
      - DATABASE_HOST=demo-mysql
      - DATABASE_USER=dbuser
      - DATABASE_PASSWORD=dbp4ss
      - DATABASE_NAME=demo
      - DATABASE_PORT=3306
    links:
      - discovery
      - configserver
      - mysql
  movie:
    image: kbastani/movie-microservice
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    depends_on:
      - mysql
    environment:
      - DATABASE_HOST=demo-mysql
      - DATABASE_USER=dbuser
      - DATABASE_PASSWORD=dbp4ss
      - DATABASE_NAME=demo
      - DATABASE_PORT=3306
    links:
      - discovery
      - configserver
      - mysql
  recommendation:
    image: kbastani/recommendation-microservice
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    depends_on:
      - mysql
    environment:
      - DATABASE_HOST=demo-mysql
      - DATABASE_USER=dbuser
      - DATABASE_PASSWORD=dbp4ss
      - DATABASE_NAME=demo
      - DATABASE_PORT=3306
    links:
     - discovery
     - configserver
  moviesui:
    image: kbastani/movies-ui
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    environment:
      - DATABASE_HOST=demo-mysql
      - DATABASE_USER=dbuser
      - DATABASE_PASSWORD=dbp4ss
      - DATABASE_NAME=demo
      - DATABASE_PORT=3306
    depends_on:
      - mysql
    ports:
      - "9006:9006"
    links:
      - discovery
      - configserver
      - mysql